version: '3.8'

services:
  api:
    build: 
      context: .
      args:
        - ENV=${ENV}
    ports:
      - "${API_PORT}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    
  db:
    image: postgres:13.14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: